/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ColumnChartExample {
        "country": string;
        "year": number;
    }
    interface FilterComponent {
    }
    interface MyComponent {
        "first": string;
        "last": string;
        "middle": string;
    }
    interface PieChartExample {
        "country": string;
        "year": number;
    }
    interface TableExample {
        "country": string;
        "year": number;
    }
}
declare global {
    interface HTMLColumnChartExampleElement extends Components.ColumnChartExample, HTMLStencilElement {
    }
    var HTMLColumnChartExampleElement: {
        prototype: HTMLColumnChartExampleElement;
        new (): HTMLColumnChartExampleElement;
    };
    interface HTMLFilterComponentElement extends Components.FilterComponent, HTMLStencilElement {
    }
    var HTMLFilterComponentElement: {
        prototype: HTMLFilterComponentElement;
        new (): HTMLFilterComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPieChartExampleElement extends Components.PieChartExample, HTMLStencilElement {
    }
    var HTMLPieChartExampleElement: {
        prototype: HTMLPieChartExampleElement;
        new (): HTMLPieChartExampleElement;
    };
    interface HTMLTableExampleElement extends Components.TableExample, HTMLStencilElement {
    }
    var HTMLTableExampleElement: {
        prototype: HTMLTableExampleElement;
        new (): HTMLTableExampleElement;
    };
    interface HTMLElementTagNameMap {
        "column-chart-example": HTMLColumnChartExampleElement;
        "filter-component": HTMLFilterComponentElement;
        "my-component": HTMLMyComponentElement;
        "pie-chart-example": HTMLPieChartExampleElement;
        "table-example": HTMLTableExampleElement;
    }
}
declare namespace LocalJSX {
    interface ColumnChartExample {
        "country"?: string;
        "year"?: number;
    }
    interface FilterComponent {
        "onFilterChange"?: (event: CustomEvent<{country: string, year: number}>) => void;
    }
    interface MyComponent {
        "first"?: string;
        "last"?: string;
        "middle"?: string;
    }
    interface PieChartExample {
        "country"?: string;
        "year"?: number;
    }
    interface TableExample {
        "country"?: string;
        "year"?: number;
    }
    interface IntrinsicElements {
        "column-chart-example": ColumnChartExample;
        "filter-component": FilterComponent;
        "my-component": MyComponent;
        "pie-chart-example": PieChartExample;
        "table-example": TableExample;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "column-chart-example": LocalJSX.ColumnChartExample & JSXBase.HTMLAttributes<HTMLColumnChartExampleElement>;
            "filter-component": LocalJSX.FilterComponent & JSXBase.HTMLAttributes<HTMLFilterComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pie-chart-example": LocalJSX.PieChartExample & JSXBase.HTMLAttributes<HTMLPieChartExampleElement>;
            "table-example": LocalJSX.TableExample & JSXBase.HTMLAttributes<HTMLTableExampleElement>;
        }
    }
}
